#!/bin/bash -l

#$ -P bf528
#$ -cwd
#$ -j y
#$ -pe mpi_16_tasks_per_node 16

##################################################################
# Data Curator: Elysha Sameth					 #    
#								 #
# Extract barcodes from each run, and count the	number of reads  #
# per distinct barcode.	For each run, plot the cumulative 	 #
# distribution and retrieve whitelist			         #
##################################################################

echo "Running job $JOB_ID"
echo "Started: $(date +%F)"
echo "Running in directory: $PWD"

# Load modules
module unload anaconda3
module load python3/3.6.5
module load umitools/1.0.0

samples=/projectnb/bf528/project_4_scrnaseq/fastq

# Read each run and extract barcode
# Read each run and extract barcode
zcat $samples/SRR3879604/SRR3879604_1_bc.fastq.gz \
$samples/SRR3879605/SRR3879605_1_bc.fastq.gz \
$samples/SRR3879606/SRR3879606_1_bc.fastq.gz > SRRX_1_bc.fastq

awk '{if(NR%4==2){print substr($1,1,19)}}' SRRX_1_bc.fastq | sort | uniq -c > merged_counts.txt

# Plot the CDF 
R --vanilla --args merged_counts.txt < plot.R 
