#!/bin/bash -l

#$ -P bf528
#$ -cwd
#$ -j y
#$ -pe mpi_16_tasks_per_node 16

##################################################################
# Data Curator: Elysha Sameth					 #    
#								 #
# Extract barcodes from each run, and count the	number of reads  #
# per distinct barcode.	For each run, plot the cumulative 	 #
# distribution and histogram, and run umi-tools to confirm 	 #
# inflection point and retrieve white-list			 #
##################################################################

echo "Running job $JOB_ID"
echo "Started: $(date +%F)"
echo "Running in directory: $PWD"

# Load modules
module unload anaconda3
module load python3/3.6.5
module load umitools/1.0.0

samples=/projectnb/bf528/project_4_scrnaseq/fastq
SRR=("SRR3879604" "SRR3879605" "SRR3879606")

# Read each run and extract barcode
for run in "${SRR[@]}"; do
	zcat $samples/$run/"$run"_1_bc.fastq.gz | 
	awk '{if(NR%4==2){print substr($1,1,19)}}' |
	sort | uniq -c > "$run"_counts.txt

	# Plot the CDF and histogram
	R --vanilla --args $run "$run"_counts.txt < plot.R 

	# Run umi-tools
	umi_tools whitelist --plot-prefix="$run"_plots \
	--extract-method=regex --bc-pattern='(?P<cell_1>.{19})(?P<umi_1>.{6})$' \
	--method=reads --error-correct-threshold=0 \
	--stdin $samples/$run/"$run"_1_bc.fastq.gz --log2stderr > "$run"_whitelist.txt
done